### ISSUE TITLE
how install latest version 0.1.1.9?

### ISSUE THREAD

**Issue by greglearns** [schell/hdevtools#10]
Sorry, noob question, but how do you install the latest version of hdevtools?

I just installed stack today (so it is the latest version) and I did `stack install hdevtools` and it gave me vesion 0.1.0.9 instead of 0.1.1.9.

```
~/a/p/h/test1 ❯❯❯ hdevtools --version
hdevtools: version 0.1.0.9 (ghc-7.8.4-x86_64-darwin, cabal-1.18.1.5)
~/a/p/h/test1 ❯❯❯ stack --version
Version 0.1.2.0, Git revision 65246552936b7da4b64b38372feac903d96a8911
~/a/p/h/test1 ❯❯❯
```

Thanks

**Comment by schell** [comment]
This is a shot in the dark, as I'm not sure how `stack` works, but maybe try running `cabal update` first? My intuition is that `stack` downloads packages from either hackage or stackage. Now that I think about it - it's most certainly stackage. http://www.stackage.org/package/hdevtools shows that 0.1.1.9 is available by the nightly builds and that 0.1.0.9 is available in LTS. I think you'll be able to figure it out from https://www.stackage.org/nightly-2015-07-08.

If that doesn't work - just use good ol' cabal + hackage. That's what I'm on.
