### ISSUE TITLE
How to get this working with stack?

### ISSUE THREAD

**Issue by seanhess** [schell/hdevtools#14]
I had this working until stack 0.1.3 came out, following these directions, but they don't work any more: http://seanhess.github.io/2015/08/05/practical-haskell-editors.html

If I run `hdevtools check` from the command-line, I get: 

    Cabal error: The program 'ghc' version >=6.4 is required but it could not be found.

hdevtools, ghc, and cabal are all on my PATH. What am I missing? Consider adding stack integration instructions to the readme?

**Comment by seanhess** [comment]
Here's some more information. I'm on OS X Yosemite. 

    $ stack --version
    Version 0.1.3.1, Git revision 908b04205e6f436d4a5f420b1c6c646ed2b804d7

    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.10.2

**Comment by schell** [comment]
Did you install with stack?

**Comment by seanhess** [comment]
:) thanks!

**Comment by seanhess** [comment]
The mystery continues... Now it's magically working and I have no idea what I changed. Maybe I upgraded hdevtools or something. 

    hdevtools: version 0.1.2.1

I'm assuming you never got the error so I'm closing. Thanks!

**Comment by seanhess** [comment]
Ok, this is weird. I went back into the project that was having the error, which I created the same way, and got the same missing ghc error. It's this project here:

https://github.com/seanhess/practical-haskell/tree/master/04-rest-api

But then I cloned the repo, and it works fine. Soo... no idea what happened there. Thanks for being awesome!

**Comment by schell** [comment]
Very odd. This may be a longshot but try puttings some lower (and upper) bounds on your dependencies, especially on `base`.

**Comment by seanhess** [comment]
Unfortunately deleting and re-cloning the project fixed the issue, so I
can't try fixes anymore. It must have been some artifact of the way I had
built it or something. It's probably safe to ignore. Thanks for your help!
