### ISSUE TITLE
Check not working in test suites

### ISSUE THREAD

**Issue by ch1bo** [schell/hdevtools#17]
Hi, when using `hdevtools check` on source files of test-suites it cannot resolve own modules and dependencies only used in the test suite, e.g. `test-framework`.

If fixed this on my fork (@7f54238b7420d44fa411ecfc057f9c0ae05ae673) by configuring ghc with the flag corresponding to `--enable-tests`. 

Now I'm not sure if this breaks things or it might be useful default? I'm happy to extend this a little and create a PR. Suggestions?

**Comment by dan-t** [comment]
Is there a reason not to merge this? @maximkulkin?

I just stumbled over the same issue. Most likely the same should be
done for benchmarks: `configBenchmarks = toFlag True`

**Comment by schell** [comment]
Yes, please submit a PR to my fork as I'm pushing up a new version to hackage soon.
