### ISSUE TITLE
Problem with Stack

### ISSUE THREAD

**Issue by davidpdrsn** [schell/hdevtools#25]
I'm developing a Yesod app and I'm having some issues getting hdevtools to work.

I get the following output

```
$ stack exec hdevtools check app/Github.hs                           
Cabal error: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with Cabal. Use the flag --package-db to specify a package database (it can be used multiple times).
```

**Comment by ch1bo** [comment]
I get the same error when running hdevtools via ``stack exec``. However, I always installed it using ``stack install`` and used the binary directly. As you might know, ``stack install`` builds the package and copies executables to a the local bin path (``stack path --local-bin-path``), which is in my PATH.

**Comment by davidpdrsn** [comment]
Uhm I might be confused but not sure how that fixes the problem. In order to install the code most typecheck, and I would like to use hdevtools to check that it does. Again I might be confused :smile:

**Comment by ch1bo** [comment]
Can you install hdevtools via stack?
    
    stack install hdevtools

After that, the ``hdevtools`` binary should be available (by default) in ``~/.local/bin``.

**Comment by davidpdrsn** [comment]
Same issue

```
$ which hdevtools
/Users/davidpdrsn/.cabal/bin/hdevtools

λ stack install hdevtools
hdevtools-0.1.2.1: download
hdevtools-0.1.2.1: configure
hdevtools-0.1.2.1: build
hdevtools-0.1.2.1: install
Copying from /Users/davidpdrsn/.stack/snapshots/x86_64-osx/lts-3.11/7.10.2/bin/hdevtools to /Users/davidpdrsn/.local/bin/hdevtools

Copied executables to /Users/davidpdrsn/.local/bin:
- hdevtools

$ which hdevtools
/Users/davidpdrsn/.stack/snapshots/x86_64-osx/lts-3.11/7.10.2/bin/hdevtools

$ stack exec hdevtools check src/Main.hs 
Cabal error: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with Cabal. Use the flag --package-db to specify a package database (it can be used multiple times).
```

**Comment by ch1bo** [comment]
Now run directly

    hdevtools check src/Main.hs

**Comment by davidpdrsn** [comment]
Still same issue 😕

**Comment by ch1bo** [comment]
Maybe you have a conflict with the cabal installed version?

**Comment by ch1bo** [comment]
I assume you do not have the erroneous environment variable ``GHC_PACKAGE_PATH`` set?

**Comment by davidpdrsn** [comment]
I don't. `env | grep GHC_PACKAGE_PATH` returns nothing. How would I check if cabal is interfering?

**Comment by ch1bo** [comment]
You could remove the version installed via cabal. Just to be sure, directly invoking the ``hdevtools`` binary produces the exact same error as you posted when calling it (with the stack env vars) via ``stack exec hdevtools``?

 I'll have a look if the version from lts-3.11 works for me, but I'm rather clueless why it should not work.

**Comment by ch1bo** [comment]
Ahh, maybe the hdevtools server of your cabal version still runs. Make sure to invoke ``hdevtools --stop-server`` in your project, or just delete the ``.hdevtools.sock`` socket file.

**Comment by davidpdrsn** [comment]
That was it! Haha :smile: 

Thanks a lot!

**Comment by ch1bo** [comment]
Your welcome, good luck with your haskell project :)

**Comment by ch1bo** [comment]
FYI: `stack exec` supports a `--no-ghc-package-path` flag as of 0.1.1.0. This means that `hdevtools` can be launched via stack (using the correct `ghc` and `ghc-pkg`), e.g.
```
stack exec --no-ghc-package-path hdevtools -- check src/Main.hs
```
I would recommend a wrapper script or `alias hdevtools="stack exec --no-ghc-package-path hdevtools -- ` though.
