### ISSUE TITLE
Unfair (outdated) description of ghc-mod

### ISSUE THREAD

**Issue by rpglover64** [schell/hdevtools#9]
From the "Credits" section:

> `hdevtools` was inspired by [ghcmod](http://www.mew.org/~kazu/proj/ghc-mod/en/), but has the advantage that due to its client-server architecture it is much faster.

However, as far as I can tell, "client-server" architecture is not what makes things fast; persisting information that ghc has stored across invocations is. `ghc-mod` introduced `ghc-modi` in commit kazu-yamamoto/ghc-mod@b40f162, which (although it doesn't do client-server) does keep the project loaded and provides a fast way to interact with it.

**Comment by schell** [comment]
Thanks :)
